package com.discovery.algorithm.calculate;




/**
 * Planets generated by hbm2java
 */
public class Planets  implements java.io.Serializable {


     private String planetnode;
     private String planetname;

    public Planets() {
    }

	
    public Planets(String planetnode) {
        this.planetnode = planetnode;
    }
    public Planets(String planetnode, String planetname) {
       this.planetnode = planetnode;
       this.planetname = planetname;
    }
   
    public String getPlanetnode() {
        return this.planetnode;
    }
    
    public void setPlanetnode(String planetnode) {
        this.planetnode = planetnode;
    }
    public String getPlanetname() {
        return this.planetname;
    }
    
    public void setPlanetname(String planetname) {
        this.planetname = planetname;
    }




}


