package com.discovery.algorithm.calculate;




/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private long rouid;
     private String planetorigin;
     private String planetdestination;
     private Double distance;

    public Routes() {
    }

	
    public Routes(long rouid) {
        this.rouid = rouid;
    }
    public Routes(long rouid, String planetorigin, String planetdestination, Double distance) {
       this.rouid = rouid;
       this.planetorigin = planetorigin;
       this.planetdestination = planetdestination;
       this.distance = distance;
    }
   
    public long getRouid() {
        return this.rouid;
    }
    
    public void setRouid(long rouid) {
        this.rouid = rouid;
    }
    public String getPlanetorigin() {
        return this.planetorigin;
    }
    
    public void setPlanetorigin(String planetorigin) {
        this.planetorigin = planetorigin;
    }
    public String getPlanetdestination() {
        return this.planetdestination;
    }
    
    public void setPlanetdestination(String planetdestination) {
        this.planetdestination = planetdestination;
    }
    public Double getDistance() {
        return this.distance;
    }
    
    public void setDistance(Double distance) {
        this.distance = distance;
    }




}


