package com.discovery.algorithm.calculate;



import java.math.BigDecimal;

/**
 * Traffic generated by hbm2java
 */
public class Traffic  implements java.io.Serializable {


     private long routeid;
     private String planetorigin;
     private String planetdestination;
     private BigDecimal traficdelay;

    public Traffic() {
    }

	
    public Traffic(long routeid) {
        this.routeid = routeid;
    }
    public Traffic(long routeid, String planetorigin, String planetdestination, BigDecimal traficdelay) {
       this.routeid = routeid;
       this.planetorigin = planetorigin;
       this.planetdestination = planetdestination;
       this.traficdelay = traficdelay;
    }
   
    public long getRouteid() {
        return this.routeid;
    }
    
    public void setRouteid(long routeid) {
        this.routeid = routeid;
    }
    public String getPlanetorigin() {
        return this.planetorigin;
    }
    
    public void setPlanetorigin(String planetorigin) {
        this.planetorigin = planetorigin;
    }
    public String getPlanetdestination() {
        return this.planetdestination;
    }
    
    public void setPlanetdestination(String planetdestination) {
        this.planetdestination = planetdestination;
    }
    public BigDecimal getTraficdelay() {
        return this.traficdelay;
    }
    
    public void setTraficdelay(BigDecimal traficdelay) {
        this.traficdelay = traficdelay;
    }




}


